USE CAMPDB;

-- 테이블 삭제 순서

DROP TABLE BOOK;

DROP TABLE CALENDAR;

DROP TABLE FACILITY;

DROP TABLE HOME;

DROP TABLE NOTICE;

DROP TABLE REVIEW;

DROP TABLE SITE;

DROP TABLE USER;

DROP TABLE ZONE;

CREATE TABLE `NOTICE` (
	`NOTICE_CODE` INT NOT NULL AUTO_INCREMENT,
	`NOTICE_LEVEL` INT NULL,
	`NOTICE_TITLE` VARCHAR(100) NULL,
	`NOTICE_WRITER` VARCHAR(50) NULL,
	`NOTICE_WRITEDATE` DATE NULL,
	`NOTICE_CONTENT` VARCHAR(500) NULL,
	PRIMARY KEY (NOTICE_CODE)
);

CREATE TABLE `SITE` (
	`SITE_CODE` INT NOT NULL AUTO_INCREMENT,
	`ZONE_CODE` INT NOT NULL,
	`SITE_NAME` VARCHAR(100) NULL,
	`SITE_PRICE` INT NULL,
	`SITE_CONTENT` LONGTEXT NULL,
	`SITE_IMG1` VARCHAR(50) NULL,
	`SITE_IMG2` VARCHAR(50) NULL,
	`SITE_IMG3` VARCHAR(50) NULL,
	`SITE_IMG4` VARCHAR(50) NULL,
	`SITE_IMG5` VARCHAR(50) NULL,
	PRIMARY KEY(SITE_CODE)
);

CREATE TABLE `REVIEW` (
	`REVIEW_CODE` INT NOT NULL AUTO_INCREMENT,
	`SITE_CODE` INT NOT NULL,
	`ID_CODE` INT NOT NULL,
	`REVIEW_CONTENT` LONGTEXT NULL,
	`REVIEW_SCORE` INT NULL,
	`REVIEW_IMG1` VARCHAR(50) NULL,
	PRIMARY KEY(REVIEW_CODE)
);

CREATE TABLE `HOME` (
	`HOME_CODE` INT NOT NULL AUTO_INCREMENT,
	`HOME_CONTENT` LONGTEXT NOT NULL,
	`HOME_IMG1` VARCHAR(30) NULL,
	`HOME_IMG2` VARCHAR(30) NULL,
	`HOME_IMG3` VARCHAR(30) NULL,
	PRIMARY KEY(HOME_CODE)
);

CREATE TABLE `FACILITY` (
	`FACILITY_CODE` INT NOT NULL AUTO_INCREMENT,
	`FACILITY_NAME` VARCHAR(100) NULL,
	`FACILITY_CONTENT` LONGTEXT NULL,
	`FACILITY_IMG1` VARCHAR(50) NULL,
	`FACILITY_IMG2` VARCHAR(50) NULL,
	`FACILITY_IMG3` VARCHAR(50) NULL,
	PRIMARY KEY(FACILITY_CODE)
);

CREATE TABLE `BOOK` (
	`BOOK_CODE` INT NOT NULL AUTO_INCREMENT,
	`CALENDAR_DATE` DATE NOT NULL,
	`SITE_CODE` INT NOT NULL,
	`ID_CODE` INT NULL,
	`BOOK_MEMBER` INT NULL,
	`BOOK_DATE` DATE NULL,
	PRIMARY KEY(BOOK_CODE)
);

CREATE TABLE `CALENDAR` (
	`CALENDAR_DATE` DATE NOT NULL,
	`CELENDAR_STATE` INT NOT NULL DEFAULT 1,
	PRIMARY KEY(CALENDAR_DATE)
);

CREATE TABLE `ZONE` (
	`ZONE_CODE` INT NOT NULL AUTO_INCREMENT,
	`ZONE_NAME` VARCHAR(30) NOT NULL,
	`ZONE_CONTENT` LONGTEXT NULL,
	`ZONE_IMG1` VARCHAR(50) NULL,
	PRIMARY KEY(ZONE_CODE)
);

CREATE TABLE `USER` (
	`ID_CODE` INT NOT NULL AUTO_INCREMENT,
	`GRANT` INT NOT NULL DEFAULT 0,
	`USER_ID` VARCHAR(20) NOT NULL,
	`USER_PASSWORD` VARCHAR(20) NOT NULL,
	`USER_NAME` VARCHAR(20) NOT NULL,
	`USER_BIRTHDAY` INT NOT NULL,
	`USER_PHONE_NUMBER` VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID_CODE)
);

ALTER TABLE `SITE` ADD CONSTRAINT `FK_ZONE_TO_SITE_1` FOREIGN KEY ( `ZONE_CODE` ) REFERENCES `ZONE` ( `ZONE_CODE` );

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_SITE_TO_SITE_1` FOREIGN KEY ( `SITE_CODE` ) REFERENCES `SITE` ( `SITE_CODE` );

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_USER_TO_REVIEW_1` FOREIGN KEY ( `ID_CODE` ) REFERENCES `USER` ( `ID_CODE` );

ALTER TABLE `BOOK` ADD CONSTRAINT `FK_CALENDAR_TO_BOOK_1` FOREIGN KEY ( `CALENDAR_DATE` ) REFERENCES `CALENDAR` ( `CALENDAR_DATE` );

ALTER TABLE `BOOK` ADD CONSTRAINT `FK_SITE_TO_BOOK_1` FOREIGN KEY ( `SITE_CODE` ) REFERENCES `SITE` ( `SITE_CODE` );

ALTER TABLE `BOOK` ADD CONSTRAINT `FK_USER_TO_BOOK_1` FOREIGN KEY ( `ID_CODE` ) REFERENCES `USER` ( `ID_CODE` );